# [START functions_ci_cd_cloud_build]
steps:
  - name: 'node:16'
    entrypoint: npm
    args: ['--version']
  - name: 'node:16'
    entrypoint: npm
    args: ['install']
    dir: '.'
  - name: 'node:16'
    entrypoint: npm
    args: ['test']
    dir: '.'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions',
      'deploy',
      'manifest',
      '--entry-point',
      'manifest',
      '--runtime', 
      'nodejs16',
      '--memory',
      '1024MB',
      '--trigger-http',
      '--allow-unauthenticated'
    ]
    dir: '.'
# [END functions_ci_cd_cloud_build]
