const fs = require('node:fs');
const path = require('node:path');

if (process.versions.node.split('.')[0] !== '22') {
  throw new Error('Use Node.js 22 to build the v2 deployment files.');
}

const root = path.resolve(__dirname, '..');
const output = path.join(root, 'build', 'gui');
const modules = ['credentials', 'resolveUrl', 'service', 'controller', 'index'];
const definitions = modules.map(name => {
  const code = fs
    .readFileSync(path.join(root, 'build', 'src', `${name}.js`), 'utf8')
    .replace(/^\/\/# sourceMappingURL=.*$/gm, '');
  return `${JSON.stringify(name)}: function(module, exports, require) {\n${code}\n}`;
});

// Keep npm dependencies external; combine only the application's CommonJS modules.
const bundle = `// Generated by npm run build. Edit src/, then rebuild.
const applicationModules = {${definitions.join(',\n')}};
const applicationCache = {};
function loadApplicationModule(name) {
  if (applicationCache[name]) return applicationCache[name].exports;
  if (!applicationModules[name]) throw new Error('Unknown module: ' + name);
  const module = {exports: {}};
  applicationCache[name] = module;
  applicationModules[name](module, module.exports, id =>
    id.startsWith('./') ? loadApplicationModule(id.slice(2)) : require(id));
  return module.exports;
}
module.exports = loadApplicationModule('index');
`;

const runtimePackage = JSON.parse(
  fs.readFileSync(path.join(root, 'package.json'), 'utf8')
);
runtimePackage.main = 'index.js';
runtimePackage.engines.node = '22.x';
runtimePackage.scripts = {start: 'functions-framework --target=manifest'};
for (const key of ['source', 'types', 'files']) delete runtimePackage[key];

const lock = JSON.parse(
  fs.readFileSync(path.join(root, 'package-lock.json'), 'utf8')
);
lock.packages[''].engines.node = '22.x';

fs.mkdirSync(output, {recursive: true});
fs.writeFileSync(path.join(output, 'index.js'), bundle);
fs.writeFileSync(
  path.join(output, 'package.json'),
  JSON.stringify(runtimePackage, null, 2) + '\n'
);
fs.writeFileSync(
  path.join(output, 'package-lock.json'),
  JSON.stringify(lock, null, 2) + '\n'
);
console.log(`GUI deployment files generated in ${output}`);
